'use client';
import { useFirstHomeBuyerCalculator } from './useFirstHomeBuyerCalculator';
import styles from './FirstHomeBuyerCalculator.module.css';

const STATES=['NSW','VIC','QLD','WA','SA','TAS','ACT','NT'];

export function FirstHomeBuyerCalculator({ className = '' }) {
  const x=useFirstHomeBuyerCalculator();
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>First home buyer inputs</h2><div className={styles.field}><label className={styles.label}>Property price</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={x.propertyPriceInput} onChange={(e)=>x.setPropertyPriceFromInput(e.target.value)} /></div></div><div className={styles.field}><label className={styles.label}>Available savings</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={x.savingsInput} onChange={(e)=>x.setSavingsFromInput(e.target.value)} /></div></div><div className={styles.field}><label className={styles.label}>State</label><select className={styles.select} value={x.state} onChange={(e)=>x.setState(e.target.value)}>{STATES.map((s)=><option key={s} value={s}>{s}</option>)}</select></div></section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Estimated LVR</p><p className={styles.primaryValue}>{x.results.lvr.toFixed(1)}%</p><p className={styles.primarySub}>{x.results.concession}</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.deposit20)}</p><p className={styles.statLabel}>20% deposit target</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.depositGap20)}</p><p className={styles.statLabel}>Gap to 20% deposit</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.deposit5)}</p><p className={styles.statLabel}>5% minimum deposit</p></div></div>{x.results.lmiRisk?<div className={[styles.banner,styles.bannerNegative].join(' ')}>LVR above 80% may trigger LMI.</div>:<div className={[styles.banner,styles.bannerPositive].join(' ')}>LVR at or below 80% reduces LMI risk.</div>}</>:<p className={styles.empty}>Enter details to estimate first-home buying position.</p>}</section></div></div>;
}
