'use client';
import { useBRRRRCalculator } from './useBRRRRCalculator';
import styles from './BRRRRCalculator.module.css';

export function BRRRRCalculator({ className = '' }) {
  const x=useBRRRRCalculator();
  const f=(label,val,onChange)=> <div className={styles.field}><label className={styles.label}>{label}</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={val} onChange={(e)=>onChange(e.target.value)} /></div></div>;
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>BRRRR assumptions</h2>{f('Purchase price',x.purchasePriceInput,x.setPurchasePriceFromInput)}{f('Rehab cost',x.rehabCostInput,x.setRehabCostFromInput)}{f('After repair value (ARV)',x.afterRepairValueInput,x.setAfterRepairValueFromInput)}{f('Weekly rent',x.weeklyRentInput,x.setWeeklyRentFromInput)}{f('Annual expenses',x.annualExpensesInput,x.setAnnualExpensesFromInput)}<div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Refinance LVR</label><span className={styles.labelRight}>{x.refiLvr}%</span></div><input className={styles.slider} type="range" min={60} max={90} value={x.refiLvr} onChange={(e)=>x.setRefiLvr(Number(e.target.value))} /></div><div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Refinance rate</label><span className={styles.labelRight}>{x.refiRate.toFixed(2)}%</span></div><input className={styles.slider} type="range" min={2} max={12} step={0.05} value={x.refiRate} onChange={(e)=>x.setRefiRate(Number(e.target.value))} /></div></section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Cash left in deal</p><p className={styles.primaryValue}>{x.formatCurrency(x.results.cashLeftInDeal)}</p><p className={styles.primarySub}>CoC ROI: {x.formatPct(x.results.coc)}</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.forcedEquity)}</p><p className={styles.statLabel}>Forced equity</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.refiAmount)}</p><p className={styles.statLabel}>Refi amount</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.annualNet)}</p><p className={styles.statLabel}>Annual net cash flow</p></div></div></>:<p className={styles.empty}>Enter assumptions to model BRRRR deal.</p>}</section></div></div>;
}
