'use client';
import { usePropertyPurchaseCostsCalculator } from './usePropertyPurchaseCostsCalculator';
import styles from './PropertyPurchaseCostsCalculator.module.css';

export function PropertyPurchaseCostsCalculator({ className = '' }) {
  const x=usePropertyPurchaseCostsCalculator();
  const currencyField=(label,value,onChange)=> <div className={styles.field}><label className={styles.label}>{label}</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={value} onChange={(e)=>onChange(e.target.value)} /></div></div>;
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>Upfront purchase costs</h2>{currencyField('Purchase price',x.purchasePriceInput,x.setPurchasePriceFromInput)}{currencyField('Stamp duty',x.stampDutyInput,x.setStampDutyFromInput)}{currencyField('Legal & conveyancing',x.legalFeesInput,x.setLegalFeesFromInput)}{currencyField('Building/pest inspections',x.inspectionsInput,x.setInspectionsFromInput)}{currencyField('Loan setup fees',x.loanFeesInput,x.setLoanFeesFromInput)}{currencyField('Moving costs',x.movingCostsInput,x.setMovingCostsFromInput)}</section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Total upfront costs</p><p className={styles.primaryValue}>{x.formatCurrency(x.results.totalCosts)}</p><p className={styles.primarySub}>excluding deposit</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.totalRequired)}</p><p className={styles.statLabel}>Property + costs</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.totalCosts)}</p><p className={styles.statLabel}>Total non-price costs</p></div></div></>:<p className={styles.empty}>Enter figures to estimate upfront costs.</p>}</section></div></div>;
}
