'use client';
import { useExtraRepaymentCalculator } from './useExtraRepaymentCalculator';
import styles from './ExtraRepaymentCalculator.module.css';

export function ExtraRepaymentCalculator({ className = '' }) {
  const x=useExtraRepaymentCalculator();
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>Extra repayment assumptions</h2>
    <div className={styles.field}><label className={styles.label}>Loan amount</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={x.loanAmountInput} onChange={(e)=>x.setLoanAmountFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><label className={styles.label}>Extra monthly repayment</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={x.extraMonthlyInput} onChange={(e)=>x.setExtraMonthlyFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><label className={styles.label}>One-off lump sum</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={x.lumpSumInput} onChange={(e)=>x.setLumpSumFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Lump sum year</label><span className={styles.labelRight}>Year {x.lumpSumYear}</span></div><input className={styles.slider} type="range" min={1} max={10} value={x.lumpSumYear} onChange={(e)=>x.setLumpSumYear(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Rate</label><span className={styles.labelRight}>{x.rate.toFixed(2)}%</span></div><input className={styles.slider} type="range" min={2} max={12} step={0.05} value={x.rate} onChange={(e)=>x.setRate(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Term</label><span className={styles.labelRight}>{x.termYears} years</span></div><input className={styles.slider} type="range" min={5} max={35} value={x.termYears} onChange={(e)=>x.setTermYears(Number(e.target.value))} /></div>
  </section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Interest saved</p><p className={styles.primaryValue}>{x.formatCurrency(x.results.interestSaved)}</p><p className={styles.primarySub}>Time saved: {Math.floor(x.results.monthsSaved/12)}y {x.results.monthsSaved%12}m</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.baseline.baseMonthly)}</p><p className={styles.statLabel}>Base repayment</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.accelerated.baseMonthly + Number(x.extraMonthlyInput.replace(/,/g,'')||0))}</p><p className={styles.statLabel}>With extra monthly</p></div></div></>:<p className={styles.empty}>Enter values to estimate savings.</p>}</section></div></div>;
}
