'use client';
import { useNegativeGearingCalculator } from './useNegativeGearingCalculator';
import styles from './NegativeGearingCalculator.module.css';

export function NegativeGearingCalculator({ className = '' }) {
  const x=useNegativeGearingCalculator();
  const cField=(label,val,onChange)=><div className={styles.field}><label className={styles.label}>{label}</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={val} onChange={(e)=>onChange(e.target.value)} /></div></div>;
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>Income, expenses and tax</h2>{cField('Annual rent',x.annualRentInput,x.setAnnualRentFromInput)}{cField('Interest cost',x.interestCostInput,x.setInterestCostFromInput)}{cField('Other cash expenses',x.otherExpensesInput,x.setOtherExpensesFromInput)}{cField('Depreciation',x.depreciationInput,x.setDepreciationFromInput)}<div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Marginal tax rate</label><span className={styles.labelRight}>{x.taxRatePct.toFixed(1)}%</span></div><input className={styles.slider} type="range" min={0} max={50} step={0.5} value={x.taxRatePct} onChange={(e)=>x.setTaxRatePct(Number(e.target.value))} /></div></section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Estimated tax benefit</p><p className={styles.primaryValue}>{x.formatCurrency(x.results.taxBenefit)}</p><p className={styles.primarySub}>{x.results.isNegativelyGeared?'Negatively geared':'Not negatively geared'}</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.taxable)}</p><p className={styles.statLabel}>Taxable property result</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.preTaxCashflow)}</p><p className={styles.statLabel}>Pre-tax cash flow</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.afterTaxCashflow)}</p><p className={styles.statLabel}>After-tax cash flow</p></div></div></>:<p className={styles.empty}>Enter values to estimate negative gearing outcome.</p>}</section></div></div>;
}
