'use client';
import { useRentVsBuyCalculator } from './useRentVsBuyCalculator';
import styles from './RentVsBuyCalculator.module.css';

export function RentVsBuyCalculator({ className = '' }) {
  const {weeklyRentInput,setWeeklyRentFromInput,homePriceInput,setHomePriceFromInput,buyingCostsInput,setBuyingCostsFromInput,depositPct,setDepositPct,rate,setRate,rentGrowthPct,setRentGrowthPct,homeGrowthPct,setHomeGrowthPct,horizonYears,setHorizonYears,results,formatCurrency}=useRentVsBuyCalculator();
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>Assumptions</h2>
    <div className={styles.field}><label className={styles.label}>Weekly rent</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={weeklyRentInput} onChange={(e)=>setWeeklyRentFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><label className={styles.label}>Home price</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={homePriceInput} onChange={(e)=>setHomePriceFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><label className={styles.label}>Upfront buying costs</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={buyingCostsInput} onChange={(e)=>setBuyingCostsFromInput(e.target.value)} /></div></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Deposit</label><span className={styles.labelRight}>{depositPct}%</span></div><input className={styles.slider} type="range" min={5} max={40} value={depositPct} onChange={(e)=>setDepositPct(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Rate</label><span className={styles.labelRight}>{rate.toFixed(2)}%</span></div><input className={styles.slider} type="range" min={2} max={12} step={0.05} value={rate} onChange={(e)=>setRate(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Rent growth</label><span className={styles.labelRight}>{rentGrowthPct.toFixed(1)}%</span></div><input className={styles.slider} type="range" min={0} max={10} step={0.5} value={rentGrowthPct} onChange={(e)=>setRentGrowthPct(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Home growth</label><span className={styles.labelRight}>{homeGrowthPct.toFixed(1)}%</span></div><input className={styles.slider} type="range" min={0} max={10} step={0.5} value={homeGrowthPct} onChange={(e)=>setHomeGrowthPct(Number(e.target.value))} /></div>
    <div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Comparison horizon</label><span className={styles.labelRight}>{horizonYears} years</span></div><input className={styles.slider} type="range" min={3} max={15} value={horizonYears} onChange={(e)=>setHorizonYears(Number(e.target.value))} /></div>
  </section><section className={styles.results}>{results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Likely better over {horizonYears} years</p><p className={styles.primaryValue}>{results.better}</p><p className={styles.primarySub}>Based on selected assumptions</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{formatCurrency(results.rentCost)}</p><p className={styles.statLabel}>Total rent paid</p></div><div className={styles.stat}><p className={styles.statValue}>{formatCurrency(results.repaymentCost)}</p><p className={styles.statLabel}>Repayments paid</p></div><div className={styles.stat}><p className={styles.statValue}>{formatCurrency(results.ownershipEquity)}</p><p className={styles.statLabel}>Projected equity</p></div><div className={styles.stat}><p className={styles.statValue}>{formatCurrency(results.buyNetPosition)}</p><p className={styles.statLabel}>Buy net position</p></div></div></>:<p className={styles.empty}>Enter assumptions to compare rent vs buy.</p>}</section></div></div>;
}
