'use client';
import { usePropertyInvestmentCalculator } from './usePropertyInvestmentCalculator';
import styles from './PropertyInvestmentCalculator.module.css';

export function PropertyInvestmentCalculator({ className = '' }) {
  const x=usePropertyInvestmentCalculator();
  const field=(label,val,onChange)=> <div className={styles.field}><label className={styles.label}>{label}</label><div className={styles.inputPrefix}><span className={styles.prefix}>$</span><input className={styles.input} type="text" inputMode="numeric" value={val} onChange={(e)=>onChange(e.target.value)} /></div></div>;
  return <div className={[styles.wrapper,className].filter(Boolean).join(' ')}><div className={styles.grid}><section className={styles.form}><h2 className={styles.formHeading}>Investment assumptions</h2>{field('Purchase price',x.purchasePriceInput,x.setPurchasePriceFromInput)}{field('Weekly rent',x.weeklyRentInput,x.setWeeklyRentFromInput)}{field('Annual non-finance expenses',x.annualExpensesInput,x.setAnnualExpensesFromInput)}<div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Deposit</label><span className={styles.labelRight}>{x.depositPct}%</span></div><input className={styles.slider} type="range" min={5} max={40} value={x.depositPct} onChange={(e)=>x.setDepositPct(Number(e.target.value))} /></div><div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Loan rate</label><span className={styles.labelRight}>{x.loanRate.toFixed(2)}%</span></div><input className={styles.slider} type="range" min={2} max={12} step={0.05} value={x.loanRate} onChange={(e)=>x.setLoanRate(Number(e.target.value))} /></div><div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Annual growth</label><span className={styles.labelRight}>{x.growthPct.toFixed(1)}%</span></div><input className={styles.slider} type="range" min={0} max={10} step={0.5} value={x.growthPct} onChange={(e)=>x.setGrowthPct(Number(e.target.value))} /></div><div className={styles.field}><div className={styles.labelRow}><label className={styles.label}>Holding period</label><span className={styles.labelRight}>{x.holdingYears} years</span></div><input className={styles.slider} type="range" min={3} max={20} value={x.holdingYears} onChange={(e)=>x.setHoldingYears(Number(e.target.value))} /></div></section><section className={styles.results}>{x.results?<><div className={styles.primaryCard}><p className={styles.primaryLabel}>Projected ROI (equity basis)</p><p className={styles.primaryValue}>{x.formatPct(x.results.roi)}</p><p className={styles.primarySub}>Over {x.holdingYears} years</p></div><div className={styles.statGrid}><div className={styles.stat}><p className={styles.statValue}>{x.formatPct(x.results.grossYield)}</p><p className={styles.statLabel}>Gross yield</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatPct(x.results.netYield)}</p><p className={styles.statLabel}>Net yield</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.capitalGain)}</p><p className={styles.statLabel}>Capital gain</p></div><div className={styles.stat}><p className={styles.statValue}>{x.formatCurrency(x.results.totalReturn)}</p><p className={styles.statLabel}>Total return estimate</p></div></div></>:<p className={styles.empty}>Enter inputs to evaluate investment metrics.</p>}</section></div></div>;
}
